export const types = {
    // CHANGE_TODO_INPUT: "CHANGE_TODO_INPUT",
    // ADD_TODO: "ADD_TODO",
    // DELETE_TODO: "DELETE_TODO",
    // CHANGE_STATUS: "CHANGE_STATUS",
    // CHANGE_TITLE: "CHANGE_TITTLE",
    // USERS:"USERS",
    //
    SEND_FORM: "SEND_FORM",
    ERROR_FORM: 'ERROR_FORM',
    CLEAR_MESSAGE: "CLEAR_MESSAGE"
}